// Batch processor used during early testing. Processes pending sources in batches.
import "dotenv/config";
import * as cheerio from "cheerio";
import fs from "fs/promises";
import { createRequire } from "module";
import * as mammoth from "mammoth";
import { db } from "./db";

const require = createRequire(import.meta.url);
const pdfParseModule = require("pdf-parse");
const BATCH_LIMIT = Number(process.env.BATCH_LIMIT || 1000);
const CHUNK_SIZE = Number(process.env.CHUNK_SIZE || 3000);
const CHUNK_OVERLAP = Number(process.env.CHUNK_OVERLAP || 400);

function normalizeText(text: string) { return text.replace(/\r/g, "\n").replace(/\t/g, " ").replace(/[ ]{2,}/g, " ").replace(/\n[ ]+/g, "\n").replace(/\n{3,}/g, "\n\n").trim(); }
function extractHtmlText(html: string) { const $ = cheerio.load(html); $(["script","style","noscript","svg","iframe","form","nav","footer","header","[class*='cookie']","[id*='cookie']","[class*='breadcrumb']","[id*='breadcrumb']","[class*='navigation']","[id*='navigation']","[class*='menu']","[id*='menu']","[class*='footer']","[id*='footer']","[class*='social']","[id*='social']"].join(",")).remove(); const title=$("title").first().text().trim(); const h1=$("h1").first().text().trim(); const mainText=$("main").text().trim()||$("#content").text().trim()||$(".content").text().trim()||$("article").text().trim()||$("body").text().trim(); return normalizeText(`${h1 || title}\n\n${mainText}`); }
async function extractPdfText(buffer: Buffer) { const defaultParser = pdfParseModule.default ?? pdfParseModule; if (typeof defaultParser === "function") { const result = await defaultParser(buffer); return normalizeText(result.text || ""); } if (pdfParseModule.PDFParse) { const parser = new pdfParseModule.PDFParse({ data: buffer }); try { const result = await parser.getText(); return normalizeText(result.text || ""); } finally { if (typeof parser.destroy === "function") await parser.destroy(); } } throw new Error("No supported pdf-parse API found."); }
async function extractDocxText(buffer: Buffer) { const result = await mammoth.extractRawText({ buffer }); return normalizeText(result.value || ""); }
function chunkText(text: string) { const chunks: string[] = []; let start=0; while(start<text.length){ const end=Math.min(start+CHUNK_SIZE,text.length); const chunk=text.slice(start,end).trim(); if(chunk.length>100) chunks.push(chunk); if(end>=text.length) break; start=end-CHUNK_OVERLAP; } return chunks; }
async function getSourcesToProcess(){ const result=await db.query(`SELECT id, university_id, url, title, source_type, raw_file_path FROM knowledge_sources WHERE raw_file_path IS NOT NULL AND status = 'pending' ORDER BY created_at ASC LIMIT $1`,[BATCH_LIMIT]); return result.rows; }
async function updateSource(params:{sourceId:string;extractedText:string;status:"processed"|"failed"}){ await db.query(`UPDATE knowledge_sources SET extracted_text=$1, status=$2, updated_at=now() WHERE id=$3`,[params.extractedText,params.status,params.sourceId]); }
async function deleteOldChunks(sourceId:string){ await db.query(`DELETE FROM knowledge_chunks WHERE source_id=$1`,[sourceId]); }
async function insertChunks(params:{sourceId:string;universityId:string;title:string|null;url:string;sourceType:string;chunks:string[]}){ for(let i=0;i<params.chunks.length;i++){ await db.query(`INSERT INTO knowledge_chunks (source_id, university_id, chunk_index, chunk_text, metadata) VALUES ($1,$2,$3,$4,$5)`,[params.sourceId,params.universityId,i,params.chunks[i],{title:params.title,url:params.url,source_type:params.sourceType}]); } }
async function processSource(source:any){ console.log(`Processing ${source.source_type}: ${source.url}`); const buffer=await fs.readFile(source.raw_file_path); let extractedText=""; if(source.source_type==="html") extractedText=extractHtmlText(buffer.toString("utf8")); else if(source.source_type==="pdf") extractedText=await extractPdfText(buffer); else if(source.source_type==="docx") extractedText=await extractDocxText(buffer); else if(source.source_type==="doc") throw new Error("Old .doc files are not supported yet. Use PDF/DOCX."); else throw new Error(`Unsupported source type: ${source.source_type}`); extractedText=normalizeText(extractedText); if(extractedText.length<100) throw new Error("Extracted text is too short or empty."); const chunks=chunkText(extractedText); await updateSource({sourceId:source.id,extractedText,status:"processed"}); await deleteOldChunks(source.id); await insertChunks({sourceId:source.id,universityId:source.university_id,title:source.title,url:source.url,sourceType:source.source_type,chunks}); console.log(`Saved ${chunks.length} chunks`); }
async function printStats(){ const s=await db.query(`SELECT status, COUNT(*)::int AS count FROM knowledge_sources GROUP BY status ORDER BY status`); const c=await db.query(`SELECT COUNT(*)::int AS count FROM knowledge_chunks`); console.log("\nSource stats:"); for(const row of s.rows) console.log(`- ${row.status}: ${row.count}`); console.log(`Chunks: ${c.rows[0].count}\n`); }
async function main(){ const sources=await getSourcesToProcess(); console.log(`Sources to process this run: ${sources.length}`); let success=0, failed=0; for(const source of sources){ try{ await processSource(source); success++; } catch(error:any){ failed++; console.error(`Failed: ${source.url}`); console.error(error.message); await updateSource({sourceId:source.id,extractedText:"",status:"failed"}); } if((success+failed)%50===0) await printStats(); } await printStats(); console.log("Processing finished."); console.log(`Successful: ${success}`); console.log(`Failed: ${failed}`); await db.end(); }
main().catch(async(error)=>{ console.error(error); await db.end(); process.exit(1); });
