import "dotenv/config";
import * as cheerio from "cheerio";
import fs from "fs/promises";
import * as mammoth from "mammoth";
import * as pdfParseModule from "pdf-parse";
import { db } from "./db";

const args = process.argv.slice(2);
const DRY_RUN = args.includes("--dry-run");
const RETRY_FAILED = args.includes("--retry-failed");
const limitArg = args.find((arg) => arg.startsWith("--limit="));
const LIMIT = limitArg ? Number(limitArg.split("=")[1]) : null;
const BATCH_SIZE = Number(process.env.BATCH_SIZE || 100);
const CHUNK_SIZE = Number(process.env.CHUNK_SIZE || 3000);
const CHUNK_OVERLAP = Number(process.env.CHUNK_OVERLAP || 400);
const MAX_FILE_BYTES = Number(process.env.MAX_FILE_BYTES || 50 * 1024 * 1024);

type SourceRow = { id: string; university_id: string; url: string; title: string | null; source_type: string; raw_file_path: string | null; };
function normalizeText(text: string) { return text.replace(/\r/g,"\n").replace(/\t/g," ").replace(/[ ]{2,}/g," ").replace(/\n[ ]+/g,"\n").replace(/\n{3,}/g,"\n\n").trim(); }
function extractHtmlText(html: string) { const $=cheerio.load(html); $(["script","style","noscript","svg","iframe","form","nav","footer","header","[class*='cookie']","[id*='cookie']","[class*='breadcrumb']","[id*='breadcrumb']","[class*='navigation']","[id*='navigation']","[class*='menu']","[id*='menu']","[class*='footer']","[id*='footer']","[class*='social']","[id*='social']","[aria-label='breadcrumb']"].join(",")).remove(); const title=$("title").first().text().trim(); const h1=$("h1").first().text().trim(); const mainText=$("main").text().trim()||$("article").text().trim()||$("#content").text().trim()||$(".content").text().trim()||$("body").text().trim(); return normalizeText(`${h1 || title}\n\n${mainText}`); }
async function extractPdfText(buffer: Buffer) { const mod: any = pdfParseModule as any; if (mod.PDFParse) { const parser = new mod.PDFParse({ data: buffer }); try { const result = await parser.getText(); return normalizeText(result.text || ""); } finally { if (typeof parser.destroy === "function") await parser.destroy(); } } const parser = mod.default ?? mod; if (typeof parser === "function") { const result = await parser(buffer); return normalizeText(result.text || ""); } throw new Error("No supported pdf-parse API found."); }
async function extractDocxText(buffer: Buffer) { const result = await mammoth.extractRawText({ buffer }); return normalizeText(result.value || ""); }
function chunkText(text: string) { const chunks: string[] = []; let start = 0; while (start < text.length) { const end = Math.min(start + CHUNK_SIZE, text.length); const chunk = text.slice(start, end).trim(); if (chunk.length > 100) chunks.push(chunk); if (end >= text.length) break; start = end - CHUNK_OVERLAP; } return chunks; }
async function ensureSchema() { await db.query(`ALTER TABLE knowledge_sources ADD COLUMN IF NOT EXISTS processing_error TEXT;`); await db.query(`ALTER TABLE knowledge_sources ADD COLUMN IF NOT EXISTS processed_at TIMESTAMP;`); }
async function resetOldProcessingRows() { await db.query(`UPDATE knowledge_sources SET status='pending', processing_error='Reset from old processing state', updated_at=now() WHERE status='processing' AND updated_at < now() - interval '2 hours';`); }
async function printStats() { const sourceStats=await db.query(`SELECT status, COUNT(*)::int AS count FROM knowledge_sources GROUP BY status ORDER BY status;`); const typeStats=await db.query(`SELECT source_type, status, COUNT(*)::int AS count FROM knowledge_sources GROUP BY source_type, status ORDER BY source_type, status;`); const chunkStats=await db.query(`SELECT COUNT(*)::int AS count FROM knowledge_chunks;`); console.log("\nSource status:"); for(const row of sourceStats.rows) console.log(`- ${row.status}: ${row.count}`); console.log("\nSource type/status:"); for(const row of typeStats.rows) console.log(`- ${row.source_type} / ${row.status}: ${row.count}`); console.log(`\nTotal chunks: ${chunkStats.rows[0].count}\n`); }
async function dryRunCheck() { console.log("Dry run mode. No files will be processed.\n"); await printStats(); const samples=await db.query(`SELECT id, source_type, url, raw_file_path FROM knowledge_sources WHERE raw_file_path IS NOT NULL AND status='pending' ORDER BY created_at ASC LIMIT 20;`); console.log("Checking sample raw files:"); let ok=0, missing=0; for(const row of samples.rows){ try{ if(!row.raw_file_path) throw new Error("Missing raw_file_path"); const stat=await fs.stat(row.raw_file_path); console.log(`OK: ${row.source_type} | ${stat.size} bytes | ${row.raw_file_path}`); ok++; } catch { console.log(`MISSING: ${row.source_type} | ${row.raw_file_path}`); missing++; } } console.log(`\nSample OK: ${ok}\nSample missing: ${missing}\n`); console.log(missing>0?"Some raw files are missing. Check storage paths before full processing.":"Dry run looks good. You can start full processing."); }
async function claimBatch() { const statuses=RETRY_FAILED?["pending","failed"]:["pending"]; const result=await db.query(`WITH candidates AS (SELECT id FROM knowledge_sources WHERE raw_file_path IS NOT NULL AND status = ANY($1) ORDER BY CASE WHEN source_type='html' THEN 1 WHEN source_type='pdf' THEN 2 WHEN source_type='docx' THEN 3 WHEN source_type='doc' THEN 4 ELSE 9 END, created_at ASC LIMIT $2 FOR UPDATE SKIP LOCKED) UPDATE knowledge_sources ks SET status='processing', processing_error=NULL, updated_at=now() FROM candidates WHERE ks.id = candidates.id RETURNING ks.id, ks.university_id, ks.url, ks.title, ks.source_type, ks.raw_file_path;`, [statuses, BATCH_SIZE]); return result.rows as SourceRow[]; }
async function markFailed(sourceId: string, errorMessage: string) { await db.query(`UPDATE knowledge_sources SET status='failed', processing_error=$1, updated_at=now() WHERE id=$2;`, [errorMessage.slice(0,5000), sourceId]); }
async function saveProcessedSource(params: { source: SourceRow; extractedText: string; chunks: string[] }) { const client=await db.connect(); try{ await client.query("BEGIN"); await client.query(`DELETE FROM knowledge_chunks WHERE source_id=$1;`, [params.source.id]); for(let i=0;i<params.chunks.length;i++){ await client.query(`INSERT INTO knowledge_chunks (source_id, university_id, chunk_index, chunk_text, metadata) VALUES ($1,$2,$3,$4,$5);`, [params.source.id, params.source.university_id, i, params.chunks[i], {title: params.source.title, url: params.source.url, source_type: params.source.source_type}]); } await client.query(`UPDATE knowledge_sources SET extracted_text=$1, status='processed', processing_error=NULL, processed_at=now(), updated_at=now() WHERE id=$2;`, [params.extractedText, params.source.id]); await client.query("COMMIT"); } catch(error){ await client.query("ROLLBACK"); throw error; } finally { client.release(); } }
async function processSource(source: SourceRow) { if(!source.raw_file_path) throw new Error("Missing raw_file_path."); const stat=await fs.stat(source.raw_file_path); if(stat.size<=0) throw new Error("Raw file is empty."); if(stat.size>MAX_FILE_BYTES) throw new Error(`File too large: ${stat.size} bytes.`); const buffer=await fs.readFile(source.raw_file_path); let extractedText=""; if(source.source_type==="html") extractedText=extractHtmlText(buffer.toString("utf8")); else if(source.source_type==="pdf") extractedText=await extractPdfText(buffer); else if(source.source_type==="docx") extractedText=await extractDocxText(buffer); else if(source.source_type==="doc") throw new Error("Old .doc files are not supported yet. Use PDF/DOCX."); else throw new Error(`Unsupported source type: ${source.source_type}`); extractedText=normalizeText(extractedText); if(extractedText.length<100) throw new Error("Extracted text is too short or empty."); const chunks=chunkText(extractedText); if(chunks.length===0) throw new Error("No chunks created from extracted text."); await saveProcessedSource({ source, extractedText, chunks }); return { textLength: extractedText.length, chunks: chunks.length }; }
async function main(){ await ensureSchema(); await resetOldProcessingRows(); console.log("CampusPaddy source processor"); console.log(`Dry run: ${DRY_RUN ? "yes" : "no"}`); console.log(`Retry failed: ${RETRY_FAILED ? "yes" : "no"}`); console.log(`Batch size: ${BATCH_SIZE}`); console.log(`Chunk size: ${CHUNK_SIZE}`); console.log(`Chunk overlap: ${CHUNK_OVERLAP}`); console.log(`Max file bytes: ${MAX_FILE_BYTES}`); console.log(`Limit: ${LIMIT ?? "none"}\n`); if(DRY_RUN){ await dryRunCheck(); await db.end(); return; } let totalProcessed=0,totalFailed=0,totalChunks=0; while(true){ if(LIMIT!==null && totalProcessed+totalFailed>=LIMIT){ console.log(`Reached limit: ${LIMIT}`); break; } const batch=await claimBatch(); if(batch.length===0){ console.log("No more pending sources."); break; } console.log(`Claimed batch: ${batch.length}`); for(const source of batch){ if(LIMIT!==null && totalProcessed+totalFailed>=LIMIT) break; try{ console.log(`Processing ${source.source_type}: ${source.url}`); const result=await processSource(source); totalProcessed++; totalChunks += result.chunks; console.log(`Processed: ${result.textLength} chars, ${result.chunks} chunks`); } catch(error:any){ totalFailed++; console.error(`Failed: ${source.url}`); console.error(error.message); await markFailed(source.id,error.message||"Unknown error"); } const completed=totalProcessed+totalFailed; if(completed%50===0){ console.log(`\nRun progress: processed=${totalProcessed}, failed=${totalFailed}, chunks=${totalChunks}`); await printStats(); } } } console.log("\nProcessing run finished."); console.log(`Processed this run: ${totalProcessed}`); console.log(`Failed this run: ${totalFailed}`); console.log(`Chunks created this run: ${totalChunks}`); await printStats(); await db.end(); }
main().catch(async(error)=>{ console.error(error); await db.end(); process.exit(1); });
